spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 1234
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /productapi
springdoc:
  swagger-ui:
    path: /swaggerui
productrestapi:
  services:
    url: http://localhost:8080/productapi/products/
    